source 'https://github.com/CocoaPods/Specs.git'

target 'MaterialDesignSpinner', :exclusive => true do
  pod "MMMaterialDesignSpinner", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MMMaterialDesignSpinner", :path => "../"

  
end
