platform :ios, '8.0'
use_frameworks!

target 'MaterialDesignSpinner', :exclusive => true do
  pod "MMMaterialDesignSpinner", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MMMaterialDesignSpinner", :path => "../"
end
